#!/bin/bash

# setup_project.sh
# Configures the current Android project for the PepperAndroid workspace.
# 1. Sets local.properties to the modern SDK.
# 2. Creates a default .vscode/launch.json if missing.
# 3. Updates the active project configuration for the workspace.

# Allow passing project root as argument, default to current directory
PROJECT_ROOT="${1:-$(pwd)}"
# Resolve absolute path
PROJECT_ROOT=$(realpath "$PROJECT_ROOT")

echo "Configuring project in: $PROJECT_ROOT"

# 1. Configure local.properties
LOCAL_PROPS="$PROJECT_ROOT/local.properties"
MODERN_SDK="/home/linda/Android/Sdk"

if [ -f "$LOCAL_PROPS" ] && grep -q "sdk.dir" "$LOCAL_PROPS"; then
    echo "local.properties already exists and has sdk.dir. Skipping SDK configuration to preserve Android Studio settings."
else
    echo "Setting sdk.dir to $MODERN_SDK in local.properties..."
    echo "sdk.dir=$MODERN_SDK" > "$LOCAL_PROPS"
fi

# Detect Package Name
MANIFEST="$PROJECT_ROOT/app/src/main/AndroidManifest.xml"
PACKAGE_NAME=""

if [ -f "$MANIFEST" ]; then
    # Try to find 'package="com.example"'
    PACKAGE_NAME=$(grep -oP 'package="\K[^"]+' "$MANIFEST")
fi

if [ -z "$PACKAGE_NAME" ]; then
    # Fallback: try to find namespace in build.gradle
    BUILD_GRADLE="$PROJECT_ROOT/app/build.gradle"
    if [ -f "$BUILD_GRADLE" ]; then
         PACKAGE_NAME=$(grep -oP "namespace\s+'\K[^']+" "$BUILD_GRADLE")
    fi
fi

if [ -z "$PACKAGE_NAME" ]; then
    echo "WARNING: Could not detect package name. Using placeholder."
    PACKAGE_NAME="com.example.myapp"
else
    echo "Detected package: $PACKAGE_NAME"
fi

# 3. Update Active Configuration for Workspace Scripts
SCRIPT_DIR=$(dirname "$(realpath "$0")")
CONFIG_FILE="$SCRIPT_DIR/.active_config"

echo "Updating active workspace configuration..."
cat <<EOF > "$CONFIG_FILE"
# Active Project Configuration
# Generated by setup_project.sh
PROJECT_DIR="$PROJECT_ROOT"
PEPPER_PACKAGE="$PACKAGE_NAME"
EOF

echo "Active project set to: $PROJECT_ROOT ($PACKAGE_NAME)"

# 2. Configure launch.json
VSCODE_DIR="$PROJECT_ROOT/.vscode"
LAUNCH_JSON="$VSCODE_DIR/launch.json"

if [ ! -d "$VSCODE_DIR" ]; then
    mkdir -p "$VSCODE_DIR"
fi

if [ ! -f "$LAUNCH_JSON" ]; then
    echo "Creating default launch.json..."
    
    MAIN_ACTIVITY="${PACKAGE_NAME}.MainActivity"

    # Create tasks.json for Smart Build
    TASKS_JSON="$VSCODE_DIR/tasks.json"
    cat <<EOF > "$TASKS_JSON"
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Smart Build (Pick Flavor)",
            "type": "shell",
            "command": "\${workspaceFolder}/../scripts/build_generic_app.py \${workspaceFolder}",
            "presentation": {
                "reveal": "always",
                "panel": "dedicated"
            },
            "isBackground": true,
            "problemMatcher": {
                "pattern": [
                    {
                        "regexp": ".",
                        "file": 1,
                        "location": 2,
                        "message": 3
                    }
                ],
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "^Starting Gradle Build",
                    "endsPattern": "^App Launched!"
                }
            }
        }
    ]
}
EOF

    # Create launch.json
    cat <<EOF > "$LAUNCH_JSON"
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "android",
            "request": "launch",
            "name": "Run on Device (Smart Build)",
            "mainActivity": "$MAIN_ACTIVITY",
            "apkFile": "\${workspaceFolder}/app/build/outputs/apk/debug/selected-debug.apk",
            "preLaunchTask": "Smart Build (Pick Flavor)",
            "deviceId": ""
        }
    ]
}
EOF
else
    echo "launch.json already exists. Skipping creation."
fi

echo "Setup complete!"
